### ISSUE TITLE
Replace iframe for WebView

### ISSUE THREAD

**Issue by causztic** [causztic/pytor-browser#1]
- iframe will only allow first load (to srcdoc)
- iframe links will not utilize the onion network
- iframe images will not utilize the onion network

**Comment by causztic** [comment]
In addition to this, we can also change `client.py` to be a server that listens to user stdin input.
With this hack we can setup the client with:
`python client.py ....server details....`
which will make it listen to input..
and then do
`www.example.com`
`www.example2.com`
for it to query the nodes and return the result in a HTTP format, kinda like a HTTP server itself. This way, I can just query `http://www.example.com` on the JS code, which gets parsed like an actual page on my side, so I need not do a lot of heavy lifting on parsing the HTML code.

**Comment by ericywl** [comment]
> In addition to this, we can also change `client.py` to be a server that listens to user stdin input.
> With this hack we can setup the client with:
> `python client.py ....server details....`
> which will make it listen to input..
> and then do
> `www.example.com`
> `www.example2.com`
> for it to query the nodes and return the result in a HTTP format, kinda like a HTTP server itself. This way, I can just query `http://www.example.com` on the JS code, which gets parsed like an actual page on my side, so I need not do a lot of heavy lifting on parsing the HTML code.

sorry 我不明白

**Comment by causztic** [comment]
为什么不明白
Ignore the first comment, typed that in a rush.. I have a better idea.

Currently client.py returns a binary string.
We can leave it as-is to demonstrate for the command-line side.

If we modify our own server instance (0th-hop) to listen to user input as well, we can maybe modify  it to become an actual HTTP server, so it can handle actual HTTP requests and responses instead of a binary string as the output.

This means that the servers are capable to pass binary strings (or a `cell`) to each other, but also return an HTTP response if it's the 0th-hop.

This way, I can implement a web query like `http://www.example.com` which gets modified to `localhost:port?html=http://www.example.com` such that it gets passed to the server instance this way. 

With this method I can make use of WebView's url rendering to render the decrypted response instead of passing in the binary string as a document (which is very hard to render and has many issues)
