### ISSUE TITLE
Can't access certain sites

### ISSUE THREAD

**Issue by Shaun2h** [causztic/pytor-browser#5]
Possibly due to the way requests module is trying to GET website, even after adding User-Agent headers
neopets.com

**Comment by ericywl** [comment]
Isn't this to do with #3?

**Comment by causztic** [comment]
No, this has to do with several sites that apparently detects us as a bot even after settting User-Agent, while #3 is about the data being truncated as it exceeds the buffer size.

**Comment by causztic** [comment]
closing because we won't fix this for the demonstration
